version: "2"

linters:
  default: all
  disable:
    # deprecated
    - wsl
    - gomodguard
    - exhaustruct

    # own style
    - depguard
    - revive
    - varnamelen
    - noinlineerr
    - recvcheck
    - musttag
    - testpackage
    - forbidigo
    - tagliatelle
