version: "2"

linters:
  default: all
  disable:
    # deprecated
    - wsl
    - gomodguard
    - exhaustruct

    # temporary
    - gochecknoglobals
    - tagliatelle
    - godox
    - funlen
    - exhaustruct_v5
    - cyclop

    # own style
    - depguard
    - revive
    - varnamelen
    - noinlineerr
    - recvcheck
    - musttag
    - testpackage
    - forbidigo
