version: "2"

linters:
  default: all
  disable:
    # deprecated
    - wsl
    # temporary
    - gochecknoglobals
    # own style
    - depguard
    - revive
    - varnamelen
    - exhaustruct
    - noinlineerr
    - recvcheck
