gin-mode = "release"
contact-us.request-timeout = "6m"

[auth]
refresh-token-ttl = '48h'
token-ttl = '2h'

[email]
sender-name = "shop-icentr.pro"
sender-email = "noreply@shop-icentr.pro"


[ftp]
enable = true
port = 8021
