// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"database/sql"
	"time"
)

type Order struct {
	ID           int64
	UserID       int64
	CreationDate time.Time
	TotalPrice   float64
}

type OrderProduct struct {
	ID           int64
	OrderID      sql.NullInt64
	ProductName  string
	Quantity     int64
	ProductPrice float64
}

type User struct {
	ID                int64
	FirstName         string
	Surname           string
	LastName          string
	Email             string
	PasswordHash      string
	CompanyName       sql.NullString
	CompanyInn        sql.NullString
	PositionInCompany sql.NullString
}
